const translations = {
  en: {
    "meta.title": "DeskLore — Computer history for your Mac",
    "meta.description":
      "DeskLore is open-source computer history for macOS: semantic-first, local-first, and built without continuous screen recording.",
    "language.label": "Language",
    "nav.home": "Back to the DeskLore home page",
    "nav.primary": "Primary navigation",
    "nav.timeline": "Timeline",
    "nav.privacy": "Privacy",
    "nav.openSource": "Open source",
    "common.viewSource": "View source",
    "hero.imageAlt": "A translucent ribbon of memories floating in deep blue space",
    "hero.titleLine1": "Your Mac,",
    "hero.titleLine2": "with a memory of its own.",
    "hero.lead":
      "Turn everyday activity into a readable timeline—without continuous screen recording or uploading raw history.",
    "hero.howItWorks": "See how it works",
    "hero.privacyBoundary": "Explore the privacy boundary",
    "manifesto.iconAlt": "DeskLore app icon",
    "manifesto.title":
      "Computer history should not be a pile of recordings. It should be readable, searchable, and yours to control.",
    "manifesto.body":
      "DeskLore focuses on apps, windows, web pages, and interaction semantics, turning scattered activity into a personal timeline.",
    "history.label": "Readable computer history",
    "history.title": "What you did today should not depend on memory alone.",
    "history.body":
      "DeskLore groups continuous events into clear activity segments, preserving time, context, and sources so your day becomes traceable again.",
    "history.imageAlt": "DeskLore timeline showing the day's activity by time",
    "privacy.title": "Consent first. Recording second.",
    "privacy.body":
      "DeskLore processes history locally by default. Visual fallback is off, sensitive surfaces are filtered, and raw events are kept only briefly.",
    "privacy.readPolicy": "Read the full privacy policy",
    "privacy.semanticLabel": "Semantics first",
    "privacy.semanticTitle": "Understand activity instead of saving the whole screen.",
    "privacy.semanticBody":
      "Apps, windows, URLs, and interactions are normalized and filtered first.",
    "privacy.visualLabel": "Visuals on demand",
    "privacy.visualTitle": "Screenshots are off by default, and raw pixels are not persisted.",
    "privacy.visualBody":
      "Window visuals are added only when semantics are insufficient and the user explicitly enables them.",
    "privacy.inspectableLabel": "Inspectable results",
    "privacy.inspectableTitle": "Timelines and memories are saved as Markdown.",
    "privacy.inspectableBody":
      "Records include source IDs and can be deleted or regenerated by the user.",
    "consent.imageAlt": "DeskLore onboarding explaining its recording and privacy boundaries",
    "consent.title": "Make the boundary clear before recording.",
    "consent.body":
      "DeskLore does not capture anything immediately on first launch. You review the recording scope before deciding whether to grant macOS Accessibility access.",
    "flow.title": "From the present moment to history you can revisit.",
    "flow.observeTitle": "Observe",
    "flow.observeBody": "Read app, window, and interaction semantics through macOS Accessibility.",
    "flow.filterTitle": "Filter",
    "flow.filterBody":
      "Remove password fields, private browsing, and sensitive system surfaces at the native capture boundary.",
    "flow.organizeTitle": "Organize",
    "flow.organizeBody":
      "Create searchable Markdown timelines and progressively roll them into long-term memory.",
    "openSource.label": "Open source",
    "openSource.title": "Your history should stay under your control.",
    "openSource.body":
      "DeskLore runs locally and is open source under Apache-2.0. You can inspect how it captures, filters, stores, and deletes data.",
    "footer.tagline": "Open-source computer history for macOS.",
    "footer.guide": "Guide",
    "footer.guideHref": "https://github.com/FoundDream/desklore/blob/main/README.md",
    "footer.privacy": "Privacy",
  },
  "zh-CN": {
    "meta.title": "DeskLore — 你的 Mac，也有记忆",
    "meta.description":
      "DeskLore 是开源的 macOS Computer History。语义优先，本地运行，不持续录屏。",
    "language.label": "语言",
    "nav.home": "返回 DeskLore 首页",
    "nav.primary": "主要导航",
    "nav.timeline": "时间线",
    "nav.privacy": "隐私设计",
    "nav.openSource": "开源",
    "common.viewSource": "查看源码",
    "hero.imageAlt": "一条半透明的记忆带漂浮在深蓝色空间中",
    "hero.titleLine1": "你的 Mac，",
    "hero.titleLine2": "也有记忆。",
    "hero.lead": "把每天的操作整理成可读时间线，不持续录屏，不上传原始历史。",
    "hero.howItWorks": "看看它如何工作",
    "hero.privacyBoundary": "了解隐私边界",
    "manifesto.iconAlt": "DeskLore 应用图标",
    "manifesto.title": "电脑历史不该是一堆录像。它应该是一段能读懂、能搜索、能由你自己掌握的记录。",
    "manifesto.body":
      "DeskLore 关注应用、窗口、网页和交互语义，把分散在一天里的操作整理成个人时间线。",
    "history.label": "可读的 Computer History",
    "history.title": "今天做了什么，不该只靠回忆。",
    "history.body":
      "DeskLore 把连续事件收束成清楚的工作片段，保留时间、上下文和来源，让一天重新变得可追溯。",
    "history.imageAlt": "DeskLore 时间线界面，按时间展示当天完成的工作",
    "privacy.title": "先同意，再记录。",
    "privacy.body":
      "DeskLore 默认在本机处理历史。视觉补充关闭，敏感界面过滤，原始事件只做短期保留。",
    "privacy.readPolicy": "阅读完整隐私说明",
    "privacy.semanticLabel": "语义优先",
    "privacy.semanticTitle": "理解操作，而不是保存整块屏幕。",
    "privacy.semanticBody": "应用、窗口、URL 和交互会先被规范化并脱敏。",
    "privacy.visualLabel": "视觉按需",
    "privacy.visualTitle": "截图默认关闭，原始像素不落盘。",
    "privacy.visualBody": "只有语义不足且用户明确开启时，才补充窗口视觉。",
    "privacy.inspectableLabel": "结果可检查",
    "privacy.inspectableTitle": "时间线和记忆最终保存为 Markdown。",
    "privacy.inspectableBody": "记录包含来源 ID，也可以由用户删除和重新生成。",
    "consent.imageAlt": "DeskLore 首次启动时展示记录范围与隐私边界",
    "consent.title": "记录之前，先把边界讲清楚。",
    "consent.body": "首次启动不会立即采集。你先确认记录范围，再决定是否授予 macOS 辅助功能权限。",
    "flow.title": "从当下，到可以回看的历史。",
    "flow.observeTitle": "观察",
    "flow.observeBody": "从 macOS Accessibility 获取应用、窗口与交互语义。",
    "flow.filterTitle": "脱敏",
    "flow.filterBody": "在原生采集边界过滤密码字段、隐私浏览和敏感系统界面。",
    "flow.organizeTitle": "整理",
    "flow.organizeBody": "生成可搜索的 Markdown 时间线，并逐步汇总为长期记忆。",
    "openSource.label": "开源",
    "openSource.title": "你的历史，应该由你掌握。",
    "openSource.body":
      "DeskLore 在本地运行，使用 Apache-2.0 许可证开源。你可以检查它如何采集、过滤、保存与删除。",
    "footer.tagline": "开源的 macOS Computer History。",
    "footer.guide": "使用说明",
    "footer.guideHref": "https://github.com/FoundDream/desklore/blob/main/README.zh-CN.md",
    "footer.privacy": "隐私",
  },
};

const supportedLocales = new Set(Object.keys(translations));
const requestedLocale = new URLSearchParams(window.location.search).get("lang");
let storedLocale;
try {
  storedLocale = window.localStorage.getItem("desklore.locale");
} catch {
  storedLocale = null;
}
const initialLocale = supportedLocales.has(requestedLocale)
  ? requestedLocale
  : supportedLocales.has(storedLocale)
    ? storedLocale
    : "en";

function applyLocale(locale) {
  const messages = translations[locale] ?? translations.en;
  document.documentElement.lang = locale;
  document.title = messages["meta.title"];
  document
    .querySelector('meta[name="description"]')
    ?.setAttribute("content", messages["meta.description"]);
  document.querySelectorAll("[data-i18n]").forEach((element) => {
    const value = messages[element.dataset.i18n];
    if (value) element.textContent = value;
  });
  document.querySelectorAll("[data-i18n-alt]").forEach((element) => {
    const value = messages[element.dataset.i18nAlt];
    if (value) element.setAttribute("alt", value);
  });
  document.querySelectorAll("[data-i18n-aria-label]").forEach((element) => {
    const value = messages[element.dataset.i18nAriaLabel];
    if (value) element.setAttribute("aria-label", value);
  });
  document.querySelectorAll("[data-i18n-href]").forEach((element) => {
    const value = messages[element.dataset.i18nHref];
    if (value) element.setAttribute("href", value);
  });
  document.querySelector(".language-switcher").value = locale;
}

const languageSwitcher = document.querySelector(".language-switcher");
languageSwitcher?.addEventListener("change", (event) => {
  const locale = event.target.value;
  if (!supportedLocales.has(locale)) return;
  try {
    window.localStorage.setItem("desklore.locale", locale);
  } catch {
    // Language switching still works when storage is unavailable.
  }
  applyLocale(locale);
});
applyLocale(initialLocale);

const requestedTheme = new URLSearchParams(window.location.search).get("theme");

if (requestedTheme === "dark" || requestedTheme === "light") {
  document.documentElement.dataset.theme = requestedTheme;
}

document.documentElement.classList.add("js");

const reveals = document.querySelectorAll(".reveal");

if (!("IntersectionObserver" in window)) {
  reveals.forEach((element) => element.classList.add("is-visible"));
} else {
  const observer = new IntersectionObserver(
    (entries) => {
      entries.forEach((entry) => {
        if (!entry.isIntersecting) return;
        entry.target.classList.add("is-visible");
        observer.unobserve(entry.target);
      });
    },
    {
      rootMargin: "0px 0px -10%",
      threshold: 0.14,
    },
  );

  reveals.forEach((element) => observer.observe(element));
}
